name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
        - uses: actions/checkout@master
        - name: Use NodeJS
          uses: actions/setup-node@master
          with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
        - run: npm install --force
        - run: npm run build

    